# Created by https://github.com/eth0izzle/security-skills/
# W4: Access Control - Credential Compromise Assessment
# Template basis: assets/loop.yaml + conditional (Entra risky users + CS Identity Protection)
# NIST IA-5 — Assess credential compromise risk by querying Entra ID Identity
# Protection risky users, MFA registration status, and optionally CrowdStrike
# Identity Protection for correlated risk signals.
# Requires Azure AD app with IdentityRiskyUser.Read.All, UserAuthenticationMethod.Read.All permissions.

name: 'Access Control - Credential Compromise Assessment'
description: >-
  For each user UPN, query Entra ID Identity Protection for risk level and
  risk detections, check MFA registration status, and optionally query
  CrowdStrike Identity Protection for correlated identity risk signals.
  Produces a per-user credential compromise risk assessment.
trigger:
    next:
        - check_gate
    name: On demand
    parameters:
        $schema: https://json-schema.org/draft-07/schema
        properties:
            user_upns:
                items:
                    type: string
                type: array
                title: User UPNs
                description: >-
                  List of user principal names (e.g. user@contoso.com) to
                  assess for credential compromise.
                minItems: 1
            tenant_id:
                type: string
                title: Azure AD Tenant ID
                description: Azure AD tenant ID for Graph API authentication.
            client_id:
                type: string
                title: Azure AD Client ID
                description: Azure AD app registration client ID.
            client_secret:
                type: string
                title: Azure AD Client Secret
                description: Azure AD app registration client secret.
            check_cs_identity_protection:
                type: boolean
                title: Check CrowdStrike Identity Protection
                description: >-
                  Query CrowdStrike Identity Protection if licensed.
                  Gracefully degrades if not available.
                default: false
            run_credential_assessment:
                type: boolean
                title: Run Credential Assessment
                description: >-
                  Gate flag — set to false to skip this workflow when called
                  from the orchestrator.
                default: true
        required:
            - user_upns
            - tenant_id
            - client_id
            - client_secret
        type: object
    type: On demand
actions:
    GetGraphToken:
        # HTTP action to acquire OAuth2 token from Azure AD
        # PLACEHOLDER_HTTP_ACTION_ID — run: action_search.py --search "http request"
        id: PLACEHOLDER_HTTP_ACTION_ID
        name: HTTP request
        next:
            - Loop
        properties:
            url: https://login.microsoftonline.com/${data['tenant_id']}/oauth2/v2.0/token
            method: POST
            headers:
                Content-Type: application/x-www-form-urlencoded
            body: >-
              grant_type=client_credentials&client_id=${data['client_id']}&client_secret=${data['client_secret']}&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default
        version_constraint: ~1
conditions:
    check_gate:
        next:
            - GetGraphToken
        cel_expression: data['run_credential_assessment'] == true
        display:
            - Credential compromise assessment is enabled
loops:
    Loop:
        display: For each User UPNs; Sequentially
        name: For each User UPNs; Sequentially
        for:
            input: user_upns
            continue_on_partial_execution: false
            sequential: true
        trigger:
            next:
                - CreateVariable
        actions:
            CreateVariable:
                id: 702d15788dbbffdf0b68d8e2f3599aa4
                class: CreateVariable
                name: Create variable
                next:
                    - QueryEntraRiskyUser
                properties:
                    variable_schema:
                        properties:
                            user_upn:
                                type: string
                            risk_level:
                                type: string
                            mfa_registered:
                                type: boolean
                            credential_compromised:
                                type: boolean
                            risk_score:
                                type: integer
                            findings:
                                type: string
                        required:
                            - user_upn
                            - risk_level
                            - mfa_registered
                            - credential_compromised
                            - risk_score
                        type: object
                version_constraint: ~1
            QueryEntraRiskyUser:
                # HTTP GET to Entra ID Identity Protection risky users endpoint.
                # Returns riskLevel (low/medium/high), riskState, and riskDetail
                # for the specified user.
                # PLACEHOLDER_HTTP_ACTION_ID — run: action_search.py --search "http request"
                id: PLACEHOLDER_HTTP_ACTION_ID
                name: HTTP request
                next:
                    - QueryMFAStatus
                properties:
                    url: >-
                      https://graph.microsoft.com/v1.0/identityProtection/riskyUsers?$filter=userPrincipalName eq '${data['user_upns.#']}'
                    method: GET
                    headers:
                        Authorization: Bearer ${data['GetGraphToken.access_token']}
                        Content-Type: application/json
                version_constraint: ~1
            QueryMFAStatus:
                # HTTP GET to Graph API authentication methods for MFA status.
                # Returns registered authentication methods (phone, FIDO2,
                # Microsoft Authenticator, etc.) to determine MFA coverage.
                # PLACEHOLDER_HTTP_ACTION_ID — run: action_search.py --search "http request"
                id: PLACEHOLDER_HTTP_ACTION_ID
                name: HTTP request
                next:
                    - check_cs_idp
                properties:
                    url: >-
                      https://graph.microsoft.com/v1.0/users/${data['user_upns.#']}/authentication/methods
                    method: GET
                    headers:
                        Authorization: Bearer ${data['GetGraphToken.access_token']}
                        Content-Type: application/json
                version_constraint: ~1
            # ── CrowdStrike Identity Protection branch (optional) ────────
            QueryCSIdentityProtection:
                # PLACEHOLDER_CS_IDENTITY_PROTECTION_ID — run: action_search.py --search "identity protection"
                # Native CrowdStrike action — queries Identity Protection for
                # correlated risk signals. Gracefully degrades if not licensed.
                id: PLACEHOLDER_CS_IDENTITY_PROTECTION_ID
                name: Query CrowdStrike Identity Protection
                next:
                    - UpdateVariableWithCSIDP
                properties:
                    user: ${data['user_upns.#']}
                version_constraint: ~1
            UpdateVariableWithCSIDP:
                id: 6c6eab39063fa3b72d98c82af60deb8a
                class: UpdateVariable
                name: Update variable - with CS IDP
                properties:
                    WorkflowCustomVariable:
                        user_upn: ${data['user_upns.#']}
                        risk_level: ${data['QueryEntraRiskyUser.body']}
                        mfa_registered: true
                        credential_compromised: false
                        risk_score: 0
                        findings: >-
                          Entra: ${data['QueryEntraRiskyUser.body']};
                          MFA: ${data['QueryMFAStatus.body']};
                          CS IDP: ${data['QueryCSIdentityProtection.body']}
                version_constraint: ~1
            # ── Standard branch (no CS Identity Protection) ──────────────
            UpdateVariable:
                id: 6c6eab39063fa3b72d98c82af60deb8a
                class: UpdateVariable
                name: Update variable
                properties:
                    WorkflowCustomVariable:
                        user_upn: ${data['user_upns.#']}
                        risk_level: ${data['QueryEntraRiskyUser.body']}
                        mfa_registered: true
                        credential_compromised: false
                        risk_score: 0
                        findings: >-
                          Entra: ${data['QueryEntraRiskyUser.body']};
                          MFA: ${data['QueryMFAStatus.body']}
                version_constraint: ~1
        conditions:
            check_cs_idp:
                next:
                    - QueryCSIdentityProtection
                cel_expression: data['check_cs_identity_protection'] == true
                display:
                    - CrowdStrike Identity Protection check is enabled
                else:
                    - UpdateVariable
        output_fields:
            - WorkflowCustomVariable.user_upn
            - WorkflowCustomVariable.risk_level
            - WorkflowCustomVariable.mfa_registered
            - WorkflowCustomVariable.credential_compromised
            - WorkflowCustomVariable.risk_score
            - WorkflowCustomVariable.findings
output_fields:
    - Loop.output
